
# services:
#   pocketbase:
#     image: ghcr.io/muchobien/pocketbase:latest
#     container_name: pocketbase
#     restart: unless-stopped
#     ports:
#       - "8090:8090"
#     volumes:
#       - ./pb_data:/pb_data
#       - ./pb_public:/pb_public
#     command:
#     - serve
#     - --http
#     - "0.0.0.0:8090"
#     - --dir
#     - /pb_data
#     - --publicDir
#     - /pb_public


# version: "3.7"
# services:
#   pocketbase:
#     image: ghcr.io/muchobien/pocketbase:latest
#     container_name: pocketbase
#     restart: unless-stopped
#     command:
#       - --encryptionEnv
#       - ENCRYPTION
#     environment:
#       ENCRYPTION: "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6" # Ganti dengan kunci 32 karakter hex
#     ports:
#       - "8090:8090"
#     volumes:
#       - ./pb_data:/pb_data
#       - ./pb_public:/pb_public
#     healthcheck:
#       test: wget --no-verbose --tries=1 --spider http://127.0.0.1:8090/api/health || exit 1
#       interval: 5s
#       timeout: 5s
#       retries: 5


version: "3.8"

services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PB_VERSION: 0.28.4
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb/pb_data
      - ./pb_public:/pb/pb_public
    environment:
      ENCRYPTION: "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6" # Ganti dengan kunci 32 karakter hex
    command:
      - /pb/pocketbase
      - serve
      - --http=0.0.0.0:8090
      - --dir=/pb/pb_data
      - --publicDir=/pb/pb_public
      - --encryptionEnv
      - ENCRYPTION
